name: Tag

on:
  push:
    tags:
      - 'v*'

jobs:

  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - name: Set $TAG env var
      run: echo "${{github.ref}}" | sed 's/refs\/tags\///' | xargs -I $ echo "::set-env name=TAG::$"
    - name: Create Github Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: docs/releases/${{ env.TAG }}.md
    
