name: Tag

on:
  push:
    tags:
      - 'v*'

jobs:

  tag:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate list of changes
      run: scripts/generate_release_notes.sh > .release.md

    - name: Create Github Release
      uses: actions/create-release@v1
      id: create-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: ./.release.md

  upload:
    name: Upload Release Artefacts
    runs-on: ubuntu-latest
    needs: tag
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - 386
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          name: 'codeownerslint'
          compress: 'true'
          dest: 'dist'
          package: 'cmd/codeownerslint'

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.tag.outputs.upload_url }}
        asset_path: ./dist/codeownerslint-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        asset_name: codeownerslint-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        asset_content_type: application/gzip
